# Cloud Build configuration for Calendar Service
steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/mobyapp-images/mobyapp-calendar:$BUILD_ID'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/mobyapp-images/mobyapp-calendar:latest'
      - '.'

  # Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/mobyapp-images/mobyapp-calendar'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'mobyapp-calendar'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/mobyapp-images/mobyapp-calendar:latest'
      - '--region=us-central1'
      - '--platform=managed'
      - '--port=8082'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=10'
      - '--allow-unauthenticated'
      - '--set-env-vars=CALENDAR_PORT=8082,URL_EUREKA=${_URL_EUREKA},SERVICE_HOSTNAME=${_SERVICE_HOSTNAME},REDIS_HOST=${_REDIS_HOST},REDIS_PORT=${_REDIS_PORT},REDIS_USERNAME=${_REDIS_USERNAME},REDIS_PASSWORD=${_REDIS_PASSWORD},REDIS_URL=${_REDIS_URL}'

substitutions:
  _URL_EUREKA: 'set-in-trigger'
  _SERVICE_HOSTNAME: 'set-in-trigger'
  _REDIS_HOST: 'set-in-trigger'
  _REDIS_PORT: 'set-in-trigger'
  _REDIS_USERNAME: 'set-in-trigger'
  _REDIS_PASSWORD: 'set-in-trigger'
  _REDIS_URL: 'set-in-trigger'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '600s'

