app = "mobyapp-ms-calendar"
primary_region = "gru"

[build]
  dockerfile = "Dockerfile"

[env]
  CALENDAR_PORT = "8082"

[[services]]
  internal_port = 8082
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[http_service]
  internal_port = 8082
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
